### ISSUE TITLE
Hi, thanks for your amazing work. I have a question about https://github.com/rohitgandikota/unified-concept-editing/blob/main/train-scripts/train_erase.py#L258.

### ISSUE THREAD

**Issue by CharlesGong12** [rohitgandikota/unified-concept-editing#11]
https://github.com/rohitgandikota/unified-concept-editing/blob/main/train-scripts/train_erase.py#L258.
This line is old_emb = old_emb[final_token_idx:len(old_emb)-max(0,farthest-final_token_idx)]. Why select old_emb from final_token_idx? I think this operation will only select <padding> tokens. Looking for your reply. Thanks again!

**Comment by rohitgandikota** [comment]
Hi @CharlesGong12 

Thanks for the question. Apologies for the late response. 

Here is an explanation from a similar issue: https://github.com/rohitgandikota/unified-concept-editing/issues/3#issuecomment-1713766843

Hope this helps

**Comment by CharlesGong12** [comment]
Thank you for addressing my issue! I appreciate your kind assistance. 💪

**Comment by rohitgandikota** [comment]
Glad I could help :)

Closing this issue
