### ISSUE TITLE
Table 2 question

### ISSUE THREAD

**Issue by MLAlex1** [rohitgandikota/unified-concept-editing#15]
Hi,

thanks for this cool work! I am a bit confused about table 2 , how do you evaluate exactly the "Accuracy of other
classes"? Do you generate 1 image per class of the 1000 classes of ImageNet or only of the classes in the table and then classify with ResNet?

Thanks!

**Comment by rohitgandikota** [comment]
Thanks for the question. Closing the issue as a duplicate. 

Answered it here: https://github.com/rohitgandikota/erasing/issues/26#issuecomment-2081510377
