### ISSUE TITLE
Code implementation different from the formula in the paper

### ISSUE THREAD

**Issue by hrz2000** [rohitgandikota/unified-concept-editing#24]
![image](https://github.com/user-attachments/assets/1e98e28a-c575-4cb9-8693-12a25e47eaf0)
what is the meaning of "mat1 = lamb * projection_matrices[layer_num].weight"? This is not seen in the formula.
![image](https://github.com/user-attachments/assets/cfa19989-bac6-4f45-846e-f802c0e173e4)
and why the Identity matrix can be preceded by a multiplied coefficient, what guarantees that the theory is true?
![image](https://github.com/user-attachments/assets/0ca979d4-8e4c-411a-a70a-37183382de34)

**Comment by raven38** [comment]
I am also confused about these points. @hrz2000 Do you have any insights?
