### ISSUE TITLE
Reproduce Sample Erasing Results

### ISSUE THREAD

**Issue by zaczywy** [rohitgandikota/unified-concept-editing#4]
Issue Description:
I am attempting to reproduce the code provided in the GitHub repository using the following commands for training and evaluation:

Training command:

`python train-scripts/train_erase.py --concepts 'violence, nudity, harm' --device '0' --concept_type 'unsafe' `

Evaluation command:

`python eval-scripts/generate-images.py --model_name="erased-violence_nudity_harm-towards_uncond-preserve_false-sd_1_4-method_replace.pt" --prompts_path 'data/unsafe-prompts4703.csv' --save_path 'evaluation_folder' --num_samples 1 --ddim_steps 50`

Actual Behavior:
However, I was unable to reproduce the expected results. I have noticed that all the generated results are meaningless patches or blobs of color.

Additional Observation:
I am using an NVIDIA RTX 3090 GPU, and the version of the diffusers library I have installed is 0.21.1.

**Comment by rohitgandikota** [comment]
Huh, this seems like a recurring issue. We are looking into it and will release a fix asap.

**Comment by rohitgandikota** [comment]
Okay so we tried it from our end and these are the results for "garbage truck" erasure.

original model

![](https://baukit.org/u/rohit/uce_test/original/3109_0.png)

edited Model

![](https://baukit.org/u/rohit/uce_test/erased-garbage%20truck-towards_-preserve_false-sd_1_4-method_replace/3109_0.png)


`python train-scripts/train_erase.py   --concepts 'Garbage Truck'   --guided_concept ' '   --device '0'   --concept_type 'object'`

eval-script:
`python eval-scripts/generate-images.py --model_name 'erased-garbage truck-towards_-preserve_false-sd_1_4-method_replace.pt' --prompts_path 'data/garbage_truck.csv' --save_path '/share/u/rohit/www/uce_test'`

**Comment by rohitgandikota** [comment]
Could you please try with diffusers version 0.20.2

**Comment by zaczywy** [comment]
Hi, I tried version 0.20.2 of diffusers, but it seems there is still no way to reproduce this above results.
<img width="1149" alt="8" src="https://github.com/rohitgandikota/unified-concept-editing/assets/65587852/684b8164-b5eb-439c-b3d9-2e816ce4f84c">

**Comment by rohitgandikota** [comment]
Could you try with `--model_name 'original'`

**Comment by rohitgandikota** [comment]
diffusers==0.20.2
imageio==2.9.0
lpips==0.1.4
matplotlib==3.6.3
NudeNet==2.0.9
numpy==1.23.3
pandas==1.5.1
Pillow==9.2.0
Pillow==10.0.1
Requests==2.31.0
sld==0.0.1
torch==2.0.1
torchvision==0.15.2
tqdm==4.64.1
transformers==4.27.4

**Comment by zaczywy** [comment]
Hi, this environment setting solves this problem. Thank you for your help. This is my requirements setting:

**Comment by rohitgandikota** [comment]
Awesome! Looking forward to any cool finding from your end.

**Comment by ShristiDasBiswas** [comment]
how long does a run take? I have been waiting on it to finish for the past 5 mins. Here is my env:

name: ucd
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_1
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.46.1=hadc24fc_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=he02047a_1
  - openssl=3.3.2=hb9d3cd8_0
  - pip=24.2=pyh8b19718_1
  - python=3.9.20=h13acc7a_1_cpython
  - readline=8.2=h8228510_1
  - setuptools=75.1.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2024b=hc8b5060_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
    - certifi==2024.8.30
    - charset-normalizer==3.4.0
    - cmake==3.30.4
    - coloredlogs==15.0.1
    - contourpy==1.3.0
    - cycler==0.12.1
    - diffusers==0.20.2
    - filelock==3.16.1
    - flatbuffers==24.3.25
    - fonttools==4.54.1
    - fsspec==2024.9.0
    - huggingface-hub==0.25.2
    - humanfriendly==10.0
    - idna==3.10
    - imageio==2.9.0
    - importlib-metadata==8.5.0
    - jinja2==3.1.4
    - kiwisolver==1.4.7
    - lazy-loader==0.4
    - lit==18.1.8
    - lpips==0.1.4
    - markupsafe==3.0.1
    - matplotlib==3.6.3
    - mpmath==1.3.0
    - networkx==3.2.1
    - nudenet==2.0.9
    - numpy==1.23.3
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - onnxruntime==1.16.3
    - opencv-python-headless==4.10.0.84
    - packaging==24.1
    - pandas==1.5.1
    - pillow==10.0.1
    - progressbar2==4.5.0
    - protobuf==5.28.2
    - pydload==1.0.9
    - pyparsing==3.2.0
    - python-dateutil==2.9.0.post0
    - python-utils==3.9.0
    - pytz==2024.2
    - pywavelets==1.6.0
    - pyyaml==6.0.2
    - regex==2024.9.11
    - requests==2.31.0
    - safetensors==0.4.5
    - scikit-image==0.20.0
    - scipy==1.9.1
    - six==1.16.0
    - sympy==1.13.3
    - tifffile==2024.8.30
    - tokenizers==0.13.3
    - torch==2.0.1
    - torchvision==0.15.2
    - tqdm==4.64.1
    - transformers==4.27.4
    - triton==2.0.0
    - typing-extensions==4.12.2
    - urllib3==2.2.3
    - zipp==3.20.2
prefix: /home/min/a/sdasbisw/anaconda3/envs/ucd
