### ISSUE TITLE
Questions about erasing objects

### ISSUE THREAD

**Issue by SLU010** [rohitgandikota/unified-concept-editing#5]
Thanks for your awesome work! 

I am intrigued by the concept of c* (or v*) that you utilized in the process of erasing objects. 

In Section 5.1.2, you have described utilizing the embedding of the 'French Horn' as c_i when it is removed. However, it appears that the specifics regarding the utilization of c* in the mapping process were not mentioned. 

Would you mind clarifying my confusion? Thank you for your time!

**Comment by rohitgandikota** [comment]
For erasing objects we use `" "` as the `c*`. 

Thanks for pointing this. We will add the info to the next arxiv version.
