### ISSUE TITLE
Query about the file for erasing 1000 artists

### ISSUE THREAD

**Issue by SLU010** [rohitgandikota/unified-concept-editing#6]
Hi, I found that the file [erased 1000 artists](https://github.com/rohitgandikota/unified-concept-editing/blob/main/data/prompts_dir/erased-1000artists-towards_art-preserve_true-sd_1_4-method_replace.csv) only contains 200 artists to be preserved. Same for the 500-artists case [here](https://github.com/rohitgandikota/unified-concept-editing/blob/main/data/prompts_dir/erased-500artists-towards_art-preserve_true-sd_1_4-method_replace.csv). I was wondering if perhaps there are small mistakes. 

Besides, I was curious to understand more about the purpose and usage of the following files: [all_artists_prompts](https://github.com/rohitgandikota/unified-concept-editing/blob/main/data/all_artists_prompts.csv) and [artists1734_prompts](https://github.com/rohitgandikota/unified-concept-editing/blob/main/data/artists1734_prompts.csv). Could you please shed some light on how these files are utilized within the project?

Thank you for your time and assistance in helping to clarify these points! 
Looking forward to understanding more about your awesome project!

**Comment by rohitgandikota** [comment]
Those are just the prompt files to test our models on for qualitative results in the paper. You can use the `artists1734.csv` file to get the list of 1734 artists and do the experiments.

**Comment by rohitgandikota** [comment]
We have done several experiments for the quantitative experiments in section 5.1.1 (we randomly sampled 1000 artists every time)

**Comment by SLU010** [comment]
Got it, thanks!
