### ISSUE TITLE
Inconsistent Results with Debiasing on All Professions in data/profession_prompts.csv

### ISSUE THREAD

**Issue by zaczywy** [rohitgandikota/unified-concept-editing#7]
Description:
When attempting to replicate the debiasing-related work, we noticed that the model's generation capability significantly decreases when applying debiasing to all professions in data/profession_prompts.csv. This seems to be inconsistent with the last row of Table 3 in the paper.

Reproduction Steps:
1.Under this method, we attempted to apply debiasing to all professions in data/profession_prompts.csv.
2.We evaluated the generated output and observed a substantial decline in generation quality.Additionally, the values of delta also differ from the reported results.

Request for Support:
Is it possible to provide the experimental code or detailed steps to assist us in replicating and validating these results? This would help us ensure the congruity of the experimental settings and outcomes as outlined in the paper, as well as gain a better understanding of the effectiveness of the method.

Thank you very much for your support and assistance! Please feel free to ask for any further contextual information or any other help you may require.

**Comment by rohitgandikota** [comment]
Hi,

Winobias has around 35 professions. So when we reported the Winibias results in the last line of Table 3 - it is for the first 35 professions in the dataset. I would consider only the first 350 rows for training UCE

**Comment by ShristiDasBiswas** [comment]
how do you create the prompts.csv files for evaluation for each erased/debiased concept? Is there a template I could use?
