### ISSUE TITLE
Question regarding the "technique" option

### ISSUE THREAD

**Issue by sandylaker** [rohitgandikota/unified-concept-editing#8]
Dear Rohit,

I enjoy a lot reading your paper and the codebase. It is an amazing work.

I do have a minor query that arose while I was navigating through the code. Specifically, I am keen to understand the distinctions between the options ["tensor"](https://github.com/rohitgandikota/unified-concept-editing/blob/f7222e63fc01fee426a61a90c0215edacbe983b6/train-scripts/train_erase.py#L267) and "replace" under the "technique" argument. (I know that "replace" means overriding the projected vector of an old concept).

I would greatly appreciate it if you could shed some light on this matter, to enhance my comprehension of the implemented methodologies. Thank you for your time and consideration.

Best regards, 
YL

**Comment by rohitgandikota** [comment]
We recommend `replace` option as that is the method we used for the paper's analysis. `tensor` method is an experiment we tested early on where we do not replace `Van Gogh` with `art` instead we remove the tensor direction of the `Van Gogh` from `art` and then replace. Didn't seem to improve the overall edit as much. Hope that made sense.
