### ISSUE TITLE
prompt in csv file for gender debiasing model

### ISSUE THREAD

**Issue by ariannaliu** [rohitgandikota/unified-concept-editing#9]
Hi, thank you so much for your great work! I really appreciate it but I have one question related to the prompt used in csv file for debasing purpose:

I want to train a debiasing model using the following command:
`python3 train-scripts/train_debias.py 
     --concept 'teacher, professor, nurse,engineer' 
     --attributes 'male, female' --device 'cuda:1'`

For the text prompt used for generation, do we need to specify the gender such as "a female teacher" to get the results or we would expect the following could generate both female and male representations?

> ,prompt,evaluation_seed,case_number
0,"photo of a teacher",3016,0
1,"photo of a teacher",3017,1
2,"photo of a teacher",3018,2

Thank you so much in advance

**Comment by rohitgandikota** [comment]
Yes, we aim to generate both male and female from just "image of a doctor." So I believe your test prompts are correct

**Comment by ariannaliu** [comment]
Thank you again! May I know if there is a way to speed up training, such as a way to modify the "preserved concept"?

**Comment by rohitgandikota** [comment]
hmm, you could probably improve the part of generating images for checking ratios at every step. One way I can think of is to either reduce the samples being generated or increase the rate at which the weights are updated. But I would be careful with these as the training could be affected. 

when you say "modify the preserved concept" I am curious to know what do you mean by that

**Comment by ariannaliu** [comment]
Thank you so much for your reply. Modify the preserved concept means shall I just comment these lines of [codes](https://github.com/rohitgandikota/unified-concept-editing/blob/f7222e63fc01fee426a61a90c0215edacbe983b6/train-scripts/train_debias.py#L329-L352) for speed up if I don't care about to preserve the ret_texts much? Thanks again

**Comment by rohitgandikota** [comment]
Oh, I see what you mean. 

I would NOT suggest commenting out the lines! Because our method pushes the debiased concepts to preservation as we try to reduce the computation.  For instance, if you are trying to de-bias doctor and teacher - and during the method doctor gets debiased first, we push it to preservation and continue the search for a teacher. If you comment out the lines, the doctor may get biased again when searching for a debiasing teacher. 

Did that make sense?

**Comment by ariannaliu** [comment]
Thank make sense to me, thank you very much!
